name: 3dsx Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-24.04
    container: devkitpro/devkitarm

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: Build
        path: |
          test.3dsx
          romfs/image.t3x
